In [61]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import numpy as np

In [ ]:
data = pd.read_html()

In [21]:
url1 = 'datasets/Monthly-BRH-US-HTG.xlsx'
url2 = 'datasets/Monthly-HOD-BRH-INF.xlsx'
url3 = 'datasets/Received-remittances.xlsx'
url5 = None
url6 = None

In [44]:
exch = pd.read_excel(url1)
exch.head()

       Date  Taux Moyen mensuel   Taux de fin de periode
0 1990-01-01                n/d                     7.805
1 1990-11-01                n/d                     8.150
2 1990-12-01                n/d                     7.850
3 1991-01-01                n/d                     7.670
4 1991-02-01                n/d                     7.725

In [45]:
exch.drop(exch.columns[1], axis=1, inplace=True)

In [46]:
exch.head()

       Date   Taux de fin de periode
0 1990-01-01                    7.805
1 1990-11-01                    8.150
2 1990-12-01                    7.850
3 1991-01-01                    7.670
4 1991-02-01                    7.725

In [47]:
exch.rename(columns={exch.columns[1]: 'end_rate'}, inplace=True)

In [48]:
exch.head()

       Date   end_rate
0 1990-01-01     7.805
1 1990-11-01     8.150
2 1990-12-01     7.850
3 1991-01-01     7.670
4 1991-02-01     7.725

In [49]:
exch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 2 columns):
Date        358 non-null datetime64[ns]
end_rate    358 non-null float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 5.6 KB

In [56]:
inf = pd.read_excel(url2)
inf

,Indicator,Indicator Name,Indicator - French Name,Indicator - Note,Measure,Measure Name,Measure - French Name,Measure - Units,Scale,Units,1999M11,1999M12,2000M1,2000M2,2000M3,2000M4,2000M5,2000M6,2000M7,2000M8,2000M9,2000M10,2000M11,2000M12,2001M1,2001M2,2001M3,2001M4,2001M5,2001M6,2001M7,2001M8,2001M9,2001M10,2001M11,2001M12,2002M1,2002M2,2002M3,2002M4,2002M5,2002M6,2002M7,2002M8,2002M9,2002M10,2002M11,2002M12,2003M1,2003M2,2003M3,2003M4,2003M5,2003M6,2003M7,2003M8,2003M9,2003M10,2003M11,2003M12,2004M1,2004M2,2004M3,2004M4,2004M5,2004M6,2004M7,2004M8,2004M9,2004M10,2004M11,2004M12,2005M1,2005M2,2005M3,2005M4,2005M5,2005M6,2005M7,2005M8,2005M9,2005M10,2005M11,2005M12,2006M1,2006M2,2006M3,2006M4,2006M5,2006M6,2006M7,2006M8,2006M9,2006M10,2006M11,2006M12,2007M1,2007M2,2007M3,2007M4,2007M5,2007M6,2007M7,2007M8,2007M9,2007M10,2007M11,2007M12,2008M1,2008M2,2008M3,2008M4,2008M5,2008M6,2008M7,2008M8,2008M9,2008M10,2008M11,2008M12,2009M1,2009M2,2009M3,2009M4,2009M5,2009M6,2009M7,2009M8,2009M9,2009M10,2009M11,2009M12,2010M1,2010M2,2010M3,2010M4,2010M5,2010M6,2010M7,2010M8,2010M9,2010M10,2010M11,2010M12,2011M1,2011M2,2011M3,2011M4,2011M5,2011M6,2011M7,2011M8,2011M9,2011M10,2011M11,2011M12,2012M1,2012M2,2012M3,2012M4,2012M5,2012M6,2012M7,2012M8,2012M9,2012M10,2012M11,2012M12,2013M1,2013M2,2013M3,2013M4,2013M5,2013M6,2013M7,2013M8,2013M9,2013M10,2013M11,2013M12,2014M1,2014M2,2014M3,2014M4,2014M5,2014M6,2014M7,2014M8,2014M9,2014M10,2014M11,2014M12,2015M1,2015M2,2015M3,2015M4,2015M5,2015M6,2015M7,2015M8,2015M9,2015M10,2015M11,2015M12,2016M1,2016M2,2016M3,2016M4,2016M5,2016M6,2016M7,2016M8,2016M9,2016M10,2016M11,2016M12,2017M1,2017M2,2017M3,2017M4,2017M5,2017M6,2017M7,2017M8,2017M9,2017M10,2017M11,2017M12,2018M1,2018M2,2018M3,2018M4,2018M5,2018M6,2018M7,2018M8,2018M9,2018M10,2018M11,2018M12,2019M1,2019M2,2019M3,2019M4,2019M5,2019M6,2019M7,2019M8,2019M9,2019M10,2019M11,2019M12,2020M1,2020M2,2020M3,2020M4,2020M5,2020M6,2020M7
0,KN.A2,General Consumer Price Index,Indice général des prix à la consommation,The weighted combination of all other indexes.,KN.B2,Monthly Inflation Rate,Variation en % sur un mois,%,units,%,0.564196,0.717535,1.153323,0.925022,2.629778,0.79366,0.302458,0.240245,0.872334,1.230196,3.944204,2.982166,1.120847,1.151785,0.748523,0.842478,0.780015,0.538635,1.037367,-0.024690,-0.036019,0.850031,0.934176,1.185752,0.642465,1.113984,0.481341,0.733379,1.213619,0.330963,0.455852,0.853685,1.007232,1.443183,1.365823,2.064441,1.518591,2.736813,6.815984,3.591478,3.222094,2.155330,1.363575,1.547773,0.789550,3.389130,3.420122,1.524838,1.508228,1.523773,1.360783,1.557590,2.925487,4.452542,1.404534,0.540928,0.234324,0.427116,2.395974,0.568455,0.558412,1.300339,1.959845,1.071501,1.034392,1.003784,1.808058,1.245319,0.947457,1.057086,1.379310,0.935374,1.179444,0.749376,1.239669,1.714286,1.043339,0.873709,1.023622,0.155885,0.622568,0.696056,1.536098,0.378215,0.226074,0.375940,0.524345,0.819672,0.517369,0.882353,1.311953,0.863309,-0.499287,0.430108,1.784440,0.631136,1.254355,1.032347,1.498638,1.610738,4.491413,1.049305,0.550482,0.951848,1.682381,0.909091,2.582583,-0.819672,-2.361275,-2.237001,-0.432900,-0.434783,-0.311915,0.125156,0.062500,0.312305,0.186800,0.621504,0.617665,0.368324,0.366972,0.548446,3.515152,-1.288056,0.533808,0.353982,0.176367,0.176056,-0.058582,0.000000,-0.058617,0.293255,0.877193,1.565217,1.141553,1.241535,1.282051,0.990644,0.653951,1.082837,0.053562,0.107066,0.641711,0.318810,0.211864,0.264271,0.632578,0.261917,0.365726,0.676731,0.465357,0.823469,0.408372,0.864260,1.058468,0.598504,0.793257,0.393507,0.293974,0.439668,0.583658,0.338491,0.481928,0.047962,0.095877,0.287356,0.095511,0.238550,0.095193,0.380409,0.236855,0.283554,0.612630,0.562061,0.536119,0.679505,0.728074,0.502513,0.363636,0.634058,0.540054,0.581916,0.400534,0.265957,0.442087,0.484155,0.832238,1.911381,2.003410,1.462599,1.194399,1.017501,0.765512,1.079568,1.068038,1.252446,0.850406,0.843235,0.684151,0.868252,1.122754,0.962250,1.319648,1.772793,1.493068,1.190893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KN.A2,General Consumer Price Index,Indice général des prix à la consommation,The weighted combination of all other indexes.,KN.B1,Yearly Inflation Rate,Variation en % sur un an,%,units,%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.552597,18.203284,18.712925,18.237854,18.141152,16.011816,15.718287,16.566146,16.258061,15.211160,14.778490,11.454722,9.510513,8.992442,8.951710,8.662774,8.545214,9.012227,8.787053,8.160935,9.111229,10.249944,10.898381,11.372640,12.339791,13.317746,15.136440,22.394984,25.867686,28.365394,30.699525,31.880531,32.788149,32.501975,35.043712,37.780532,37.052102,37.038113,35.420068,28.504028,25.981013,25.619009,28.443859,28.495760,27.221726,26.520891,22.896171,21.679156,20.532917,19.405086,19.142299,19.846452,19.272826,17.081374,13.215644,13.666169,14.462517,15.276879,16.000000,14.848266,15.267283,15.979155,15.348354,14.533612,15.262011,15.272218,15.123768,14.236734,13.007507,12.643803,12.241379,12.414966,11.794440,10.741049,10.330579,9.551020,8.587480,8.022240,8.031496,8.339829,9.105058,7.888631,7.603687,7.866868,8.138659,9.248120,9.962547,11.028316,11.899483,16.323529,16.516035,15.640288,15.741797,18.279570,18.843683,19.775596,18.048780,13.833448,10.149864,8.053691,5.878468,1.011378,0.087577,-0.398159,-1.029149,-2.484848,-2.762763,-4.625293,-3.482881,-0.785973,2.040816,6.086957,5.177792,6.070088,6.312500,6.433479,6.288917,6.028589,5.373687,4.665439,4.587156,5.118830,6.181818,3.747073,6.405694,7.197640,7.877719,8.392019,9.373169,9.495897,9.613130,10.381232,10.409357,9.681159,8.276256,7.731377,6.688963,5.723720,5.395095,5.197618,4.927691,5.299786,6.096257,6.535600,6.832627,7.452431,7.590933,7.228916,7.419018,7.652264,7.290589,7.308286,6.482899,6.151500,5.544355,4.538653,4.164601,3.443187,3.429691,3.370787,3.210117,3.239845,3.469880,3.525682,4.179178,4.837165,5.062082,5.343511,5.759162,6.229196,6.442444,6.616257,6.597549,6.416862,6.334420,6.647618,7.952518,9.319324,10.363636,11.277174,11.701170,11.951656,12.505563,13.253546,14.367816,14.832746,15.243101,15.073849,13.895993,12.912662,12.355848,12.494912,13.336019,14.154338,14.280063,14.1,13.9,14.3,14.6,15.5,15.8,15.6,15.6,15.4,14.4,13.7,13.3,13.2,13.2,12.9,13.0,12.7,13.0,13.6,14.1,14.6,14.3,14.5,15.1,15.5,17.0,16.7,17.7,18.0,18.6,19.1,19.5,19.7,20.0,20.4,20.8,20.7,20.8,22.0,22.3,23.4,NaN,NaN
2,KN.A2,General Consumer Price Index,Indice général des prix à la consommation,The weighted combination of all other indexes.,KN.B3,"Index, August 2004 = 100","Indice, Août 2004=100","Index, August 2004 = 100",units,"index, August 2004 = 100",43.300000,43.700000,44.200000,44.600000,45.700000,46.10000,46.200000,46.400000,46.800000,47.300000,49.200000,50.700000,51.200000,51.800000,52.200000,52.700000,53.100000,53.400000,53.900000,53.900000,53.900000,54.300000,54.800000,55.500000,55.800000,56.500000,56.700000,57.200000,57.900000,58.000000,58.300000,58.800000,59.400000,60.300000,61.100000,62.300000,63.300000,65.000000,69.400000,71.900000,74.300000,75.900000,76.900000,78.100000,78.700000,81.400000,84.200000,85.400000,86.700000,88.000000,89.200000,90.600000,93.300000,97.400000,98.800000,99.300000,99.600000,100.000000,102.400000,103.000000,103.600000,104.900000,107.000000,108.100000,109.200000,110.300000,112.300000,113.700000,114.800000,116.000000,117.600000,118.700000,120.100000,121.000000,122.500000,124.600000,125.900000,127.000000,128.300000,128.500000,129.300000,130.200000,132.200000,132.700000,133.000000,133.500000,134.200000,135.300000,136.000000,137.200000,139.000000,140.200000,139.500000,140.100000,142.600000,143.500000,145.300000,146.800000,149.000000,151.400000,158.200000,159.900000,160.700000,162.300000,165.000000,166.500000,170.800000,169.400000,165.400000,161.700000,161.000000,160.300000,159.800000,160.000000,160.100000,160.600000,160.900000,161.900000,162.900000,163.500000,164.100000,165.000000,170.800000,168.600000,169.500000,170.100000,170.400000,170.700000,170.600000,170.600000,170.500000,171.000000,172.500000,175.200000,177.200000,179.400000,181.700000,183.500000,184.700000,186.700000,186.800000,187.000000,188.200000,188.800000,189.200000,189.700000,190.900000,191.400000,192.100000,193.400000,194.300000,195.900000,196.700000,198.400000,200.500000,201.700000,203.300000,204.100000,204.700000,205.600000,206.800000,207.500000,208.500000,208.600000,208.800000,209.400000,209.600000,210.100000,210.300000,211.100000,211.600000,212.200000,213.500000,214.700000,215.900000,217.300000,218.900000,220.000000,220.800000,222.200000,223.400000,224.700000,225.600000,226.200000,227.200000,228.300000,230.200000,234.600000,239.300000,242.800000,245.700000,248.200000,250.100000,252.800000,255.500000,258.700000,260.900000,263.100000,264.900000,267.200000,270.200000,272.800000,276.400000,281.300000,285.500000,288.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Source:,Haitian Institute of Statistics and Informatics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Download URL:,http://opendata.investhaiti.ht/HTINFLA2016V1/i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
inf = inf.loc[1, '2000M10': '2020M5']

In [91]:
exch['inf'] = np.nan
for i in range(len(inf)):
    exch.loc[120+i, 'inf'] = inf[i]

In [92]:
exch

         Date   end_rate        inf
0   1990-01-01    7.8050        NaN
1   1990-11-01    8.1500        NaN
2   1990-12-01    7.8500        NaN
3   1991-01-01    7.6700        NaN
4   1991-02-01    7.7250        NaN
5   1991-03-01    7.9650        NaN
6   1991-04-01    7.5250        NaN
7   1991-05-01    7.4500        NaN
8   1991-06-01    7.5900        NaN
9   1991-07-01    7.3300        NaN
10  1991-08-01    7.3300        NaN
11  1991-09-01    7.4850        NaN
12  1991-10-01    8.1300        NaN
13  1991-11-01    8.3000        NaN
14  1991-12-01    8.2400        NaN
15  1992-01-01    8.5490        NaN
16  1992-02-01    8.7780        NaN
17  1992-03-01    8.9110        NaN
18  1992-04-01    9.2700        NaN
19  1992-05-01    9.7260        NaN
20  1992-06-01    9.7970        NaN
21  1992-07-01    9.5050        NaN
22  1992-08-01    9.8560        NaN
23  1992-09-01   10.1780        NaN
24  1992-10-01   10.5090        NaN
25  1992-11-01   11.3540        NaN
26  1992-12-01   10.9530        NaN
27  1993-01-01   12.2949        NaN
28  1993-02-01   11.0000        NaN
29  1993-03-01   12.8344        NaN
30  1993-04-01   13.4196        NaN
31  1993-05-01   14.4485        NaN
32  1993-06-01   13.6558        NaN
33  1993-07-01   12.3758        NaN
34  1993-08-01   12.4661        NaN
35  1993-09-01   12.3966        NaN
36  1993-10-01   12.4866        NaN
37  1993-11-01   13.1677        NaN
38  1993-12-01   12.8049        NaN
39  1994-01-01   13.7755        NaN
40  1994-02-01   13.8890        NaN
41  1994-03-01   14.2177        NaN
42  1994-04-01   14.9482        NaN
43  1994-05-01   14.8599        NaN
44  1994-06-01   14.6436        NaN
45  1994-07-01   17.1647        NaN
46  1994-08-01   21.4932        NaN
47  1994-09-01   15.0964        NaN
48  1994-10-01   14.2828        NaN
49  1994-11-01   14.0546        NaN
50  1994-12-01   12.9466        NaN
51  1995-01-01   14.1560        NaN
52  1995-02-01   13.9795        NaN
53  1995-03-01   14.4729        NaN
54  1995-04-01   14.2410        NaN
55  1995-05-01   14.6439        NaN
56  1995-06-01   15.0698        NaN
57  1995-07-01   15.0173        NaN
58  1995-08-01   15.6292        NaN
59  1995-09-01   15.5384        NaN
60  1995-10-01   17.0236        NaN
61  1995-11-01   16.1755        NaN
62  1995-12-01   16.1599        NaN
63  1996-01-01   16.7830        NaN
64  1996-02-01   16.5518        NaN
65  1996-03-01   16.8024        NaN
66  1996-04-01   16.3635        NaN
67  1996-05-01   16.0997        NaN
68  1996-06-01   15.5882        NaN
69  1996-07-01   15.0446        NaN
70  1996-08-01   15.0343        NaN
71  1996-09-01   15.0454        NaN
72  1996-10-01   15.5525        NaN
73  1996-11-01   15.2733        NaN
74  1996-12-01   15.0928        NaN
75  1997-01-01   16.2599        NaN
76  1997-02-01   16.1117        NaN
77  1997-03-01   16.5056        NaN
78  1997-04-01   16.6913        NaN
79  1997-05-01   16.8170        NaN
80  1997-06-01   16.7564        NaN
81  1997-07-01   16.4850        NaN
82  1997-08-01   16.7518        NaN
83  1997-09-01   16.9496        NaN
84  1997-10-01   17.4131        NaN
85  1997-11-01   16.8719        NaN
86  1997-12-01   17.3110        NaN
87  1998-01-01   17.5602        NaN
88  1998-02-01   17.3752        NaN
89  1998-03-01   17.3427        NaN
90  1998-04-01   16.9492        NaN
91  1998-05-01   16.6870        NaN
92  1998-06-01   15.6646        NaN
93  1998-07-01   16.0670        NaN
94  1998-08-01   16.5075        NaN
95  1998-09-01   16.8475        NaN
96  1998-10-01   16.3043        NaN
97  1998-11-01   16.5948        NaN
98  1998-12-01   16.5046        NaN
99  1999-01-01   16.7778        NaN
100 1999-02-01   16.8943        NaN
101 1999-03-01   16.6816        NaN
102 1999-04-01   16.6876        NaN
103 1999-05-01   16.6990        NaN
104 1999-06-01   16.7046        NaN
105 1999-07-01   16.8242        NaN
106 1999-08-01   16.7961        NaN
107 1999-09-01   16.9411        NaN
108 1999-10-01   17.5482        NaN
109 1999-11-01   17.9632        NaN
110 1999-12-01   17.9654        NaN
111 2000-01-01   18.2620        NaN
112 2000-02-01   19.1848        NaN
113 2000-03-01   19.7373        NaN
114 2000-04-01   19.7265        NaN
115 2000-05-01   19.6744        NaN
116 2000-06-01   20.3781        NaN
117 2000-07-01   20.8679        NaN
118 2000-08-01   21.6345        NaN
119 2000-09-01   28.3337        NaN
120 2000-10-01   23.5820  17.552597
121 2000-11-01   23.8881  18.203284
122 2000-12-01   22.5242  18.712925
123 2001-01-01   23.7612  18.237854
124 2001-02-01   23.5483  18.141152
125 2001-03-01   23.9641  16.011816
126 2001-04-01   23.4651  15.718287
127 2001-05-01   23.5197  16.566146
128 2001-06-01   24.3731  16.258061
129 2001-07-01   24.1052  15.211160
130 2001-08-01   24.4244  14.778490
131 2001-09-01   25.4927  11.454722
132 2001-10-01   26.0076   9.510513
133 2001-11-01   25.9602   8.992442
134 2001-12-01   26.3389   8.951710
135 2002-01-01   26.6744   8.662774
136 2002-02-01   27.1982   8.545214
137 2002-03-01   26.7658   9.012227
138 2002-04-01   26.6768   8.787053
139 2002-05-01   26.9701   8.160935
140 2002-06-01   27.2819   9.111229
141 2002-07-01   28.4377  10.249944
142 2002-08-01   28.7608  10.898381
143 2002-09-01   29.6984  11.372640
144 2002-10-01   32.9547  12.339791
145 2002-11-01   37.2729  13.317746
146 2002-12-01   37.6092  15.136440
147 2003-01-01   41.5097  22.394984
148 2003-02-01   44.5181  25.867686
149 2003-03-01   42.2152  28.365394
150 2003-04-01   42.3014  30.699525
151 2003-05-01   40.5400  31.880531
152 2003-06-01   42.8573  32.788149
153 2003-07-01   42.7099  32.501975
154 2003-08-01   41.2170  35.043712
155 2003-09-01   42.0253  37.780532
156 2003-10-01   41.9623  37.052102
157 2003-11-01   42.8229  37.038113
158 2003-12-01   42.0849  35.420068
159 2004-01-01   44.0850  28.504028
160 2004-02-01   44.0038  25.981013
161 2004-03-01   40.2165  25.619009
162 2004-04-01   37.7444  28.443859
163 2004-05-01   36.9540  28.495760
164 2004-06-01   35.7358  27.221726
165 2004-07-01   36.0315  26.520891
166 2004-08-01   36.0958  22.896171
167 2004-09-01   36.8229  21.679156
168 2004-10-01   37.1563  20.532917
169 2004-11-01   37.4848  19.405086
170 2004-12-01   37.2318  19.142299
171 2005-01-01   37.6915  19.846452
172 2005-02-01   37.8931  19.272826
173 2005-03-01   38.2039  17.081374
174 2005-04-01   39.0311  13.215644
175 2005-05-01   38.7025  13.666169
176 2005-06-01   39.9245  14.462517
177 2005-07-01   42.0759  15.276879
178 2005-08-01   42.3415  16.000000
179 2005-09-01   43.0426  14.848266
180 2005-10-01   43.0291  15.267283
181 2005-11-01   43.0612  15.979155
182 2005-12-01   43.0003  15.348354
183 2006-01-01   43.4757  14.533612
184 2006-02-01   42.9775  15.262011
185 2006-03-01   42.6885  15.272218
186 2006-04-01   41.0963  15.123768
187 2006-05-01   39.0188  14.236734
188 2006-06-01   39.8619  13.007507
189 2006-07-01   39.9548  12.643803
190 2006-08-01   38.8615  12.241379
191 2006-09-01   39.1292  12.414966
192 2006-10-01   39.1312  11.794440
193 2006-11-01   38.9958  10.741049
194 2006-12-01   37.5914  10.330579
195 2007-01-01   38.9823   9.551020
196 2007-02-01   38.3217   8.587480
197 2007-03-01   37.4215   8.022240
198 2007-04-01   36.9035   8.031496
199 2007-05-01   36.5716   8.339829
200 2007-06-01   35.7429   9.105058
201 2007-07-01   35.6388   7.888631
202 2007-08-01   35.7562   7.603687
203 2007-09-01   36.3813   7.866868
204 2007-10-01   36.3602   8.138659
205 2007-11-01   37.1785   9.248120
206 2007-12-01   36.7844   9.962547
207 2008-01-01   37.5434  11.028316
208 2008-02-01   37.7222  11.899483
209 2008-03-01   38.7147  16.323529
210 2008-04-01   38.4124  16.516035
211 2008-05-01   38.8782  15.640288
212 2008-06-01   39.5597  15.741797
213 2008-07-01   39.7740  18.279570
214 2008-08-01   39.9945  18.843683
215 2008-09-01   39.9535  19.775596
216 2008-10-01   39.9601  18.048780
217 2008-11-01   40.3273  13.833448
218 2008-12-01   39.8176  10.149864
219 2009-01-01   40.4392   8.053691
220 2009-02-01   40.4601   5.878468
221 2009-03-01   40.7022   1.011378
222 2009-04-01   40.7963   0.087577
223 2009-05-01   40.8162  -0.398159
224 2009-06-01   41.1596  -1.029149
225 2009-07-01   41.4482  -2.484848
226 2009-08-01   41.4335  -2.762763
227 2009-09-01   41.7737  -4.625293
228 2009-10-01   42.0271  -3.482881
229 2009-11-01   42.2804  -0.785973
230 2009-12-01   42.0193   2.040816
231 2010-01-01   38.7000   6.086957
232 2010-02-01   38.6375   5.177792
233 2010-03-01   39.6156   6.070088
234 2010-04-01   39.5097   6.312500
235 2010-05-01   39.7925   6.433479
236 2010-06-01   39.7991   6.288917
237 2010-07-01   39.8392   6.028589
238 2010-08-01   39.8522   5.373687
239 2010-09-01   39.9405   4.665439
240 2010-10-01   40.0954   4.587156
241 2010-11-01   40.1493   5.118830
242 2010-12-01   39.8817   6.181818
243 2011-01-01   40.3363   3.747073
244 2011-02-01   40.3803   6.405694
245 2011-03-01   40.2588   7.197640
246 2011-04-01   40.2540   7.877719
247 2011-05-01   40.2586   8.392019
248 2011-06-01   40.3239   9.373169
249 2011-07-01   40.4165   9.495897
250 2011-08-01   40.6484   9.613130
251 2011-09-01   40.8742  10.381232
252 2011-10-01   41.0060  10.409357
253 2011-11-01   41.0958   9.681159
254 2011-12-01   40.9734   8.276256
255 2012-01-01   41.3309   7.731377
256 2012-02-01   41.5340   6.688963
257 2012-03-01   41.5810   5.723720
258 2012-04-01   41.7230   5.395095
259 2012-05-01   41.9112   5.197618
260 2012-06-01   41.9761   4.927691
261 2012-07-01   42.0188   5.299786
262 2012-08-01   42.1923   6.096257
263 2012-09-01   42.3222   6.535600
264 2012-10-01   42.4121   6.832627
265 2012-11-01   42.5778   7.452431
266 2012-12-01   42.5530   7.590933
267 2013-01-01   42.7534   7.228916
268 2013-02-01   42.8610   7.419018
269 2013-03-01   43.0166   7.652264
270 2013-04-01   43.3461   7.290589
271 2013-05-01   43.6803   7.308286
272 2013-06-01   43.7922   6.482899
273 2013-07-01   43.7326   6.151500
274 2013-08-01   43.7555   5.544355
275 2013-09-01   43.7429   4.538653
276 2013-10-01   43.8080   4.164601
277 2013-11-01   43.8496   3.443187
278 2013-12-01   43.8820   3.429691
279 2014-01-01   44.0151   3.370787
280 2014-02-01   44.3479   3.210117
281 2014-03-01   44.7062   3.239845
282 2014-04-01   44.9934   3.469880
283 2014-05-01   44.3551   3.525682
284 2014-06-01   45.3399   4.179178
285 2014-07-01   45.3552   4.837165
286 2014-08-01   45.3829   5.062082
287 2014-09-01   45.5577   5.343511
288 2014-10-01   45.7572   5.759162
289 2014-11-01   46.5991   6.229196
290 2014-12-01   46.7477   6.442444
291 2015-01-01   46.9277   6.616257
292 2015-02-01   47.1441   6.597549
293 2015-03-01   47.1789   6.416862
294 2015-04-01   47.3801   6.334420
295 2015-05-01   48.1113   6.647618
296 2015-06-01   51.5866   7.952518
297 2015-07-01   55.2174   9.319324
298 2015-08-01   51.6674  10.363636
299 2015-09-01   52.1417  11.277174
300 2015-10-01   53.7793  11.701170
301 2015-11-01   56.1368  11.951656
302 2015-12-01   56.6970  12.505563
303 2016-01-01   59.4546  13.253546
304 2016-02-01   61.4393  14.367816
305 2016-03-01   61.7627  14.832746
306 2016-04-01   61.9572  15.243101
307 2016-05-01   62.2054  15.073849
308 2016-06-01   62.8939  13.895993
309 2016-07-01   63.6545  12.912662
310 2016-08-01   64.8864  12.355848
311 2016-09-01   65.5368  12.494912
312 2016-10-01   66.3278  13.336019
313 2016-11-01   67.0629  14.154338
314 2016-12-01   67.3944  14.280063
315 2017-01-01   67.7976  14.100000
316 2017-02-01   68.3332  13.900000
317 2017-03-01   69.3523  14.300000
318 2017-04-01   67.6004  14.600000
319 2017-05-01   62.2023  15.500000
320 2017-06-01   62.3516  15.800000
321 2017-07-01   62.4717  15.600000
322 2017-08-01   62.6587  15.600000
323 2017-09-01   62.6900  15.400000
324 2017-10-01   62.9405  14.400000
325 2017-11-01   63.3030  13.700000
326 2017-12-01   63.6871  13.300000
327 2018-01-01   63.8271  13.200000
328 2018-02-01   64.1154  13.200000
329 2018-03-01   65.2715  12.900000
330 2018-04-01   65.5747  13.000000
331 2018-05-01   66.1431  12.700000
332 2018-06-01   66.9070  13.000000
333 2018-07-01   67.7221  13.600000
334 2018-08-01   69.1096  14.100000
335 2018-09-01   69.9774  14.600000
336 2018-10-01   72.2672  14.300000
337 2018-11-01   74.6114  14.500000
338 2018-12-01   77.1881  15.100000
339 2019-01-01   81.0353  15.500000
340 2019-02-01   82.0249  17.000000
341 2019-03-01   82.6061  16.700000
342 2019-04-01   86.0961  17.700000
343 2019-05-01   92.5356  18.000000
344 2019-06-01   93.0256  18.600000
345 2019-07-01   93.2599  19.100000
346 2019-08-01   93.3893  19.500000
347 2020-09-01   93.3162  19.700000
348 2020-10-01   91.7459  20.000000
349 2020-11-01   91.7155  20.400000
350 2020-12-01   91.9842  20.800000
351 2020-01-01   92.7940  20.700000
352 2020-02-01   94.7716  20.800000
353 2020-03-01   97.9700  22.000000
354 2020-04-01  102.8348  22.300000
355 2020-05-01  108.9426  23.400000
356 2020-06-01  113.3133        NaN
357 2020-07-01  119.6463        NaN
358        NaT       NaN        NaN
359        NaT       NaN        NaN
360        NaT       NaN        NaN
361        NaT       NaN        NaN
362        NaT       NaN        NaN
363        NaT       NaN        NaN
364        NaT       NaN        NaN
365        NaT       NaN        NaN

In [96]:
rem = pd.read_excel(url3)
rem = rem.drop(rem.index[0:6]).reset_index(drop=True)

In [97]:
rem.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,octobre 19,novembre 19,décembre 19,janvier 20,février 20,mars 20,avril 20,mai 20,juin 20,juillet 20,août 20,septembre 20,Exercice 2019-2020
1,USA,1.27488e+08,1.32652e+08,1.97052e+08,1.38773e+08,1.56526e+08,1.84221e+08,NaN,NaN,NaN,NaN,NaN,NaN,9.36711e+08
2,FRANCE,7.37397e+06,6.24767e+06,9.89007e+06,6.01436e+06,6.40578e+06,5.40965e+06,NaN,NaN,NaN,NaN,NaN,NaN,4.13415e+07
3,CANADA,6.49759e+06,6.70704e+06,1.02147e+07,5.8803e+06,5.67559e+06,6.26491e+06,NaN,NaN,NaN,NaN,NaN,NaN,4.12402e+07
4,REP DOMINICAINE,6.22933e+06,5.9522e+06,8.51945e+06,5.37145e+06,6.84166e+06,6.11951e+06,NaN,NaN,NaN,NaN,NaN,NaN,3.90336e+07
5,MARTINIQUE,2.47909e+06,3.33216e+06,5.01228e+06,3.01626e+06,3.05412e+06,2.41565e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.93095e+07
6,CHILI,1.00959e+07,1.16815e+07,1.74563e+07,1.1524e+07,1.14766e+07,9.61742e+06,NaN,NaN,NaN,NaN,NaN,NaN,7.18517e+07
7,BRESIL,4.9206e+06,5.19739e+06,9.45012e+06,5.24702e+06,5.3025e+06,4.38787e+06,NaN,NaN,NaN,NaN,NaN,NaN,3.45055e+07
8,SAINT MARTIN,94728,115280,121703,80777.4,94217.1,100976,NaN,NaN,NaN,NaN,NaN,NaN,607681
9,BAHAMAS,3.68076e+06,3.99259e+06,5.24634e+06,3.69254e+06,4.18049e+06,3.71019e+06,NaN,NaN,NaN,NaN,NaN,NaN,2.45029e+07
10,TURKS & CAICOS,2.43505e+06,2.76696e+06,3.7981e+06,3.12257e+06,3.30864e+06,3.61293e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.90442e+07
11,AUTRES ANTILLES,1.46247e+06,1.5219e+06,2.15587e+06,1.42327e+06,1.52935e+06,1.36579e+06,NaN,NaN,NaN,NaN,NaN,NaN,9.45865e+06
12,AFRIQUE,113686,76708.8,105782,88906.4,93253.3,99154.1,NaN,NaN,NaN,NaN,NaN,NaN,577490
13,AUTRES AMERIQUE DU SUD,2.92198e+06,2.43501e+06,4.45166e+06,579312,606581,489301,NaN,NaN,NaN,NaN,NaN,NaN,1.14838e+07
14,AMERIQUE CENTRALE,473271,468635,926176,525654,556403,505440,NaN,NaN,NaN,NaN,NaN,NaN,3.45558e+06
15,ASIE,98514.8,116584,139032,117296,105388,112672,NaN,NaN,NaN,NaN,NaN,NaN,689486
16,AUTRES PAYS D'EUROPE,2.32917e+06,1.38513e+06,2.79878e+06,735471,712548,758400,NaN,NaN,NaN,NaN,NaN,NaN,8.7195e+06
17,TOTAL ( Formel),1.78694e+08,1.84649e+08,2.77338e+08,1.86192e+08,2.06469e+08,2.29191e+08,0,0,0,0,0,0,1.26253e+09
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
rem = rem.drop(rem.index[1:17]).reset_index(drop=True)
rem.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,octobre 19,novembre 19,décembre 19,janvier 20,février 20,mars 20,avril 20,mai 20,juin 20,juillet 20,août 20,septembre 20,Exercice 2019-2020
1,TOTAL ( Formel),1.78694e+08,1.84649e+08,2.77338e+08,1.86192e+08,2.06469e+08,2.29191e+08,0,0,0,0,0,0,1.26253e+09
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total global ( formel + informel),2.38326e+08,2.40034e+08,3.70388e+08,2.51883e+08,2.72544e+08,3.01471e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Source: BRH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Exercice 2018-2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,octobre 18,novembre 18,décembre 18,janvier 19,février 19,mars 19,avril 19,mai 19,juin 19,juillet 19,août 19,septembre 19,Exercice 2018-2019
12,USA,1.35368e+08,1.23697e+08,1.82674e+08,1.21325e+08,1.28341e+08,1.83898e+08,1.6573e+08,1.56554e+08,1.39665e+08,1.44834e+08,1.5032e+08,1.27505e+08,1.75991e+09
13,FRANCE,8.01236e+06,7.03349e+06,1.04016e+07,7.33643e+06,6.93463e+06,8.12919e+06,8.00875e+06,7.92397e+06,7.3631e+06,7.82067e+06,8.55241e+06,7.29724e+06,9.48138e+07
14,CANADA,9.68009e+06,8.4968e+06,1.31582e+07,8.29335e+06,8.16134e+06,9.55759e+06,1.01574e+07,9.63616e+06,8.18632e+06,9.02028e+06,9.13668e+06,7.31741e+06,1.10802e+08
15,REP DOMINICAINE,5.90036e+06,5.28099e+06,7.62205e+06,4.88321e+06,5.70784e+06,6.53208e+06,6.16814e+06,6.4803e+06,6.42649e+06,6.61569e+06,6.71214e+06,6.55092e+06,7.48802e+07
16,MARTINIQUE,3.20622e+06,2.93225e+06,4.62376e+06,2.88641e+06,2.61354e+06,2.97914e+06,3.05077e+06,2.91769e+06,2.54041e+06,2.68374e+06,2.7957e+06,2.44721e+06,3.56768e+07
17,CHILI,1.31587e+07,1.27254e+07,2.10245e+07,1.42529e+07,1.51019e+07,1.68093e+07,1.62459e+07,1.52904e+07,1.37658e+07,1.38708e+07,1.43803e+07,1.13136e+07,1.7794e+08
18,BRESIL,5.045e+06,4.72948e+06,8.93541e+06,5.05337e+06,4.96988e+06,5.24273e+06,5.38065e+06,5.31555e+06,5.17874e+06,5.60191e+06,5.63191e+06,4.87245e+06,6.59571e+07
19,SAINT MARTIN,146439,115973,206211,134579,113286,147582,135234,99360.6,121818,121169,143275,109945,1.59487e+06

In [80]:
rem.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
5,Exercice 2019-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,octobre 19,novembre 19,décembre 19,janvier 20,février 20,mars 20,avril 20,mai 20,juin 20,juillet 20,août 20,septembre 20,Exercice 2019-2020
7,USA,1.27488e+08,1.32652e+08,1.97052e+08,1.38773e+08,1.56526e+08,1.84221e+08,NaN,NaN,NaN,NaN,NaN,NaN,9.36711e+08
8,FRANCE,7.37397e+06,6.24767e+06,9.89007e+06,6.01436e+06,6.40578e+06,5.40965e+06,NaN,NaN,NaN,NaN,NaN,NaN,4.13415e+07
9,CANADA,6.49759e+06,6.70704e+06,1.02147e+07,5.8803e+06,5.67559e+06,6.26491e+06,NaN,NaN,NaN,NaN,NaN,NaN,4.12402e+07
10,REP DOMINICAINE,6.22933e+06,5.9522e+06,8.51945e+06,5.37145e+06,6.84166e+06,6.11951e+06,NaN,NaN,NaN,NaN,NaN,NaN,3.90336e+07
11,MARTINIQUE,2.47909e+06,3.33216e+06,5.01228e+06,3.01626e+06,3.05412e+06,2.41565e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.93095e+07
12,CHILI,1.00959e+07,1.16815e+07,1.74563e+07,1.1524e+07,1.14766e+07,9.61742e+06,NaN,NaN,NaN,NaN,NaN,NaN,7.18517e+07
13,BRESIL,4.9206e+06,5.19739e+06,9.45012e+06,5.24702e+06,5.3025e+06,4.38787e+06,NaN,NaN,NaN,NaN,NaN,NaN,3.45055e+07
14,SAINT MARTIN,94728,115280,121703,80777.4,94217.1,100976,NaN,NaN,NaN,NaN,NaN,NaN,607681
15,BAHAMAS,3.68076e+06,3.99259e+06,5.24634e+06,3.69254e+06,4.18049e+06,3.71019e+06,NaN,NaN,NaN,NaN,NaN,NaN,2.45029e+07
16,TURKS & CAICOS,2.43505e+06,2.76696e+06,3.7981e+06,3.12257e+06,3.30864e+06,3.61293e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.90442e+07
17,AUTRES ANTILLES,1.46247e+06,1.5219e+06,2.15587e+06,1.42327e+06,1.52935e+06,1.36579e+06,NaN,NaN,NaN,NaN,NaN,NaN,9.45865e+06
18,AFRIQUE,113686,76708.8,105782,88906.4,93253.3,99154.1,NaN,NaN,NaN,NaN,NaN,NaN,577490
19,AUTRES AMERIQUE DU SUD,2.92198e+06,2.43501e+06,4.45166e+06,579312,606581,489301,NaN,NaN,NaN,NaN,NaN,NaN,1.14838e+07
20,AMERIQUE CENTRALE,473271,468635,926176,525654,556403,505440,NaN,NaN,NaN,NaN,NaN,NaN,3.45558e+06
21,ASIE,98514.8,116584,139032,117296,105388,112672,NaN,NaN,NaN,NaN,NaN,NaN,689486
22,AUTRES PAYS D'EUROPE,2.32917e+06,1.38513e+06,2.79878e+06,735471,712548,758400,NaN,NaN,NaN,NaN,NaN,NaN,8.7195e+06
23,TOTAL ( Formel),1.78694e+08,1.84649e+08,2.77338e+08,1.86192e+08,2.06469e+08,2.29191e+08,0,0,0,0,0,0,1.26253e+09
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
rem.drop(rem.index[2:-2], inplace=True)

In [82]:
rem.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
5,Exercice 2019-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,octobre 19,novembre 19,décembre 19,janvier 20,février 20,mars 20,avril 20,mai 20,juin 20,juillet 20,août 20,septembre 20,Exercice 2019-2020
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,Source: BRH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN